name: Nightly

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-latest
            ext: ~
            runtime: linux-x64
          - name: Windows
            os: windows-latest
            ext: .exe
            runtime: win-x64

    env:
      proj: "Totk.ZStdTool"

    steps:
      - uses: actions/checkout@master

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Publish Totk ZStd Tool
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          -o ${{ matrix.config.name }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: ZSTD-Tool-${{ matrix.config.name }}
          path: ${{ matrix.config.name }}/${{ env.proj }}${{ matrix.config.ext }}
