name: Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - name: Linux
            os: ubuntu-latest
            ext: ~
            runtime: linux-x64
          - name: Windows
            os: windows-latest
            ext: .exe
            runtime: win-x64

    env:
      proj: "TotkZstdTool"

    steps:
      - uses: actions/checkout@master

      - name: Install DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish Totk ZStd Tool
        shell: bash
        run: |
          dotnet publish src/${{ env.proj }}.csproj \
          -r ${{ matrix.config.runtime }} \
          -c Release \
          --sc false \
          --version-suffix ${{ github.event.release.tag_name }} \
          -o ${{ matrix.config.name }} \
          -p:Version=${{ github.event.release.tag_name }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishReadyToRun=true

      - name: Upload artifacts
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: zstd-tool${{ matrix.config.ext }}
          path: ${{ matrix.config.name }}/${{ env.proj }}${{ matrix.config.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
